name: flutter_clean_starter
description: Skip the boilerplate. Start building Flutter apps the right way.
version: 0.1.5
homepage: https://github.com/rajoanrahman100/flutter_clean_starter
repository: https://github.com/rajoanrahman100/flutter_clean_starter
issue_tracker: https://github.com/rajoanrahman100/flutter_clean_starter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  flutter_clean_starter: flutter_clean_starter
